---
- name: copy ip addres node1 
  hosts: node1
  vars:
    ip_address: 172.31.45.45
  tasks: 
    - name: copy ip address to the nodes
      ansible.builtin.copy:
        content: "Private ip address of this node is {{ ip_address }}"
        dest: /home/ec2-user/myfile2

    - name: using debug module
      ansible.builtin.debug:
        var: ip_address
        # msg: En büyük galatasarayli hidayet ali